# Generated by Django 6.0.4 on 2026-04-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
